version: '2'
services:
  migrator_samuele:
      image: beeckup/imap-migrator:latest
      environment:
        - FROMMAIL=samuele@nutellino.it
        - FROMPASSWORD=REDACTED
        - FROMHOST=mail.nutellino.it
        - FROMSSL= # Empty equals false, 1 equals true
        - FROMIGNORE_FOLDERS=
        - TOMAIL=test@gmail.com
        - TOPASSWORD=REDACTED
        - TOHOST=imap.gmail.com
        - TOSSL= # Empty equals false, 1 equals true
        - TOROOT_FOLDER=[Gmail] # SWITCH TO "MIGRATION" FOLDER FOR ZIMBRA
        # - STRIP_INBOX=INBOX
      volumes:
        - ./database/:/database/

